packages:
  - '.'
  - examples/*

overrides:
  supports-color: '8.1.1'

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  esbuild: false
  sharp: false
  '@swc/core': true
minimumReleaseAgeStrict: false
