import type { SchemaEnum, StaticField, StaticModel, StaticSchema } from '../schema/types.js';

const SCALARS: Readonly<Record<string, string>> = {
  String: 'string',
  Boolean: 'boolean',
  Int: 'number',
  Float: 'number',
  BigInt: 'bigint',
  DateTime: 'Date',
  Decimal: 'string',
  Bytes: 'Uint8Array',
  Json: 'unknown',
};

function fieldType(field: StaticField): string {
  const base = field.enumName !== null ? field.enumName : (SCALARS[field.type] ?? 'unknown');
  if (field.isList) return `readonly ${base}[]`;
  return field.isRequired ? base : `${base} | null`;
}

function emitEnum(value: SchemaEnum): string {
  const members = value.values.map((v) => JSON.stringify(v)).join(' | ');
  return `export type ${value.name} = ${members};`;
}

function emitModel(model: StaticModel): string {
  const fields = model.fields.map((f) => `  readonly ${f.name}: ${fieldType(f)};`);
  return [`export interface ${model.model} {`, ...fields, '}'].join('\n');
}

export function emitModelTypesModule(schema: StaticSchema): string {
  const models = [...schema.models].sort((a, b) => a.model.localeCompare(b.model));
  const enums = [...schema.enums].sort((a, b) => a.name.localeCompare(b.name));

  const lines: string[] = [
    '// Code generated by pgbase. DO NOT EDIT.',
    '//',
    '// Row types as a client receives them, for `createClient<PgbaseModels>()`. Types only, so',
    '// importing this from a browser bundle costs nothing at runtime.',
    '//',
    '// A policy `omit` is NOT reflected here — the generator runs at `prisma generate` time and',
    '// policies are TypeScript. Omit those fields where you build the client:',
    "//   type AuditLog = Omit<Models.AuditLog, 'actorId'>",
    '',
  ];

  if (enums.length > 0) lines.push(...enums.map(emitEnum), '');
  lines.push(...models.flatMap((model) => [emitModel(model), '']));

  lines.push(
    '/** Every model, keyed by Prisma model name — the shape `createClient` expects. */',
    'export interface PgbaseModels {',
    ...models.map((m) => `  readonly ${m.model}: ${m.model};`),
    '}',
    '',
  );

  return lines.join('\n');
}
