import type { StaticSchema } from '../schema/types.js';

export interface EmitOptions {
  readonly packageSpecifier: string;
}

export function emitStaticSchemaModule(schema: StaticSchema, options: EmitOptions): string {
  const lines: string[] = [
    '// Code generated by pgbase. DO NOT EDIT.',
    '//',
    '// Build output — gitignore it alongside the Prisma client. Regenerated by the same',
    '// `prisma generate` you already run.',
    '',
    `import type { StaticSchema } from '${options.packageSpecifier}';`,
    '',
    'export default ' + formatValue(schema, 0) + ' satisfies StaticSchema;',
    '',
  ];
  return lines.join('\n');
}

function formatValue(value: unknown, depth: number): string {
  if (value === null) return 'null';
  if (value === undefined) return 'undefined';
  if (typeof value === 'string') return JSON.stringify(value);
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (Array.isArray(value)) return formatArray(value, depth);
  if (typeof value === 'object') return formatObject(value as Record<string, unknown>, depth);
  throw new Error(`Cannot emit value of type ${typeof value}`);
}

function formatArray(arr: readonly unknown[], depth: number): string {
  if (arr.length === 0) return '[]';
  const inner = pad(depth + 1);
  const items = arr.map((item) => `${inner}${formatValue(item, depth + 1)},`);
  return `[\n${items.join('\n')}\n${pad(depth)}]`;
}

function formatObject(obj: Record<string, unknown>, depth: number): string {
  const keys = Object.keys(obj);
  if (keys.length === 0) return '{}';
  const inner = pad(depth + 1);
  const entries = keys.map(
    (key) => `${inner}${formatKey(key)}: ${formatValue(obj[key], depth + 1)},`,
  );
  return `{\n${entries.join('\n')}\n${pad(depth)}}`;
}

const IDENTIFIER_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function formatKey(key: string): string {
  return IDENTIFIER_RE.test(key) ? key : JSON.stringify(key);
}

function pad(depth: number): string {
  return '  '.repeat(depth);
}
