import type { PgbaseModels } from '@api/generated/pgbase/models';
import { createClient, type GetAuth } from '@dltech/pgbase/client';
import { useSyncExternalStore } from 'react';
import { io } from 'socket.io-client';

export const API_URL = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:3001';

// ─────────────────────────────────────────────────────────────────────────────
// Row types
// ─────────────────────────────────────────────────────────────────────────────
// Generated by the same `prisma generate` the API runs, so a column added or retyped in the schema
// is a compile error here rather than a runtime surprise. Two things the generator cannot know,
// because policies are TypeScript and it runs before them — both have to be restated:
//
//   - a model with NO_CLIENT_ACCESS is not reachable at all (JobSettings)
//   - a column a policy `omit`s never reaches the wire (AuditLog.actorId)
//
// `Decimal` arrives as `string` (Invoice.amount): 18 digits of precision do not survive a JS
// number, and the server was given no `decimalConstructor`.

export type JobStatus = PgbaseModels['Job']['status'];
export type Job = PgbaseModels['Job'];
export type Task = PgbaseModels['Task'];
export type Invoice = PgbaseModels['Invoice'];
export type Org = PgbaseModels['Org'];
export type AuditLog = Omit<PgbaseModels['AuditLog'], 'actorId'>;

type Models = Omit<PgbaseModels, 'AuditLog' | 'JobSettings'> & { readonly AuditLog: AuditLog };

// ─────────────────────────────────────────────────────────────────────────────
// Identity
// ─────────────────────────────────────────────────────────────────────────────
// Stands in for a login. Alice and Bob share an org, so two windows signed in as the two of them
// are a real collaborative session; Carol is in a different org and proves the isolation.

export const DEV_USERS = {
  alice: {
    id: '00000000-0000-4000-8000-0000000000a1',
    name: 'Alice Chen',
    org: 'Northwind Robotics',
  },
  bob: { id: '00000000-0000-4000-8000-0000000000a2', name: 'Bob Osei', org: 'Northwind Robotics' },
  carol: { id: '00000000-0000-4000-8000-0000000000b1', name: 'Carol Vega', org: 'Acme Freight' },
} as const;

export type DevUser = keyof typeof DEV_USERS;

const SESSION_KEY = 'pgbase-example-user';

let currentUser: DevUser = 'alice';
const userListeners = new Set<() => void>();

export function getCurrentUser(): DevUser {
  return currentUser;
}

export function getAuthHeaders(): Record<string, string> {
  return { 'x-pgbase-dev-user': DEV_USERS[currentUser].id };
}

const getAuth: GetAuth = () => getAuthHeaders();

// Creating the client opens nothing; the socket connects lazily on the first live query.
export const pgbase = createClient<Models>({
  baseUrl: API_URL,
  getAuth,
  createSocket: (baseUrl, opts) => io(baseUrl, opts),
});

export function setCurrentUser(next: DevUser): void {
  if (next === currentUser) return;
  currentUser = next;
  window.sessionStorage.setItem(SESSION_KEY, next);
  // Same getter, but re-setting it reconnects the socket, so every open subscription resyncs under
  // the new claims instead of keeping rows the previous identity was allowed to see.
  pgbase.$setAuth(getAuth);
  for (const listener of userListeners) listener();
}

/** Per-tab, so two windows can hold two identities across reloads. Called once, after mount. */
export function restoreCurrentUser(): void {
  const stored = window.sessionStorage.getItem(SESSION_KEY);
  if (stored !== null && stored in DEV_USERS) setCurrentUser(stored as DevUser);
}

export function useCurrentUser(): DevUser {
  return useSyncExternalStore(
    (listener) => {
      userListeners.add(listener);
      return () => userListeners.delete(listener);
    },
    getCurrentUser,
    () => 'alice' as DevUser,
  );
}
